name: Deploy to ECS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full repository to avoid missing files

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Use your AWS region

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t taskmaster:${{ github.sha }} .

      # Step 5: Tag the Docker image as "latest"
      - name: Tag Docker image as "latest"
        run: docker tag taskmaster:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # Step 6: Push both the unique SHA image and the "latest" tag
      - name: Push Docker images to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}  # Push the SHA-tagged image
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest 
